# Generated by Django 2.2.3 on 2020-01-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200116_1551'),
        ('posts', '0006_auto_20200116_1539'),
    ]

    operations = [
    ]
