# Generated by Django 2.2.3 on 2020-01-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0008_merge_20200116_1601")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                help_text="This field determines the url path of this post. It defaults to the title.",
                null=True,
                unique=True,
            ),
        )
    ]
